version: '2'
services:
  droppy:
    container_name: droppy
    image: silverwind/droppy
    ports:
      - '8989:8989'
    volumes:
      - ./config:/config
      - /home/grid/eipi10/jian-xu3/snps-analysis/data/storage:/files
    restart: unless-stopped
