version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: microsheen/get-started:part2
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    deploy:
      placement:
        constraints: [node.role != manager]
    ports:
      - "8800:80"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8888:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
   # volumes:
   #   - "./data:/data"
    deploy:
      placement:
        constraints: [node.role != manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet:
